namespace FSharp.Units

open Microsoft.FSharp.Core

module DataTransferRate =

    [<Measure>]
    type bps = // bits per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<bps> value
        static member toKiloBitsPerSecond(value : float<bps>) = kbps.create(float value / 1000.)
        static member toMegaBitsPerSecond(value : float<bps>) = Mbps.create(float value / 1e+6)
        static member toGigaBitsPerSecond(value : float<bps>) = Gbps.create(float value / 1e+9)
        static member toTeraBitsPerSecond(value : float<bps>) = Tbps.create(float value / 1e+12)
        static member toKiloBytesPerSecond(value : float<bps>) = kBps.create(float value / 8000.)
        static member toMegaBytesPerSecond(value : float<bps>) = MBps.create(float value / 8e+6)
        static member toGigaBytesPerSecond(value : float<bps>) = GBps.create(float value / 8e+9)
        static member toTeraBytesPerSecond(value : float<bps>) = TBps.create(float value / 8e+12)
        static member toKibibitPerSecond(value : float<bps>) = Kibitps.create(float value / 1024.)
        static member toMebibitPerSecond(value : float<bps>) = Mibit.create(float value / 1.049e+6)
    and [<Measure>] kbps = // kilo bits per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<kbps> value
        static member toBitsPerSecond(value : float<kbps>) = bps.create(float value * 1000.)
        static member toMegaBitsPerSecond(value : float<kbps>) = Mbps.create(float value / 1000.)
        static member toGigaBitsPerSecond(value : float<kbps>) = Gbps.create(float value / 1e+6)
        static member toTeraBitsPerSecond(value : float<kbps>) = Tbps.create(float value / 1e+9)
        static member toKiloBytesPerSecond(value : float<kbps>) = kBps.create(float value / 8.)
        static member toMegaBytesPerSecond(value : float<kbps>) = MBps.create(float value / 8000.)
        static member toGigaBytesPerSecond(value : float<kbps>) = GBps.create(float value / 8e+6)
        static member toTeraBytesPerSecond(value : float<kbps>) = TBps.create(float value / 8e+9)
        static member toKibibitPerSecond(value : float<kbps>) = Kibitps.create(float value / 1.024)
        static member toMebibitPerSecond(value : float<kbps>) = Mibit.create(float value / 1049.)
    and [<Measure>] Mbps = // Mega bits per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<Mbps> value
        static member toBitsPerSecond(value : float<Mbps>) = bps.create(float value * 1e+6)
        static member toKiloBitsPerSecond(value : float<Mbps>) = kbps.create(float value * 1000.)
        static member toGigaBitsPerSecond(value : float<Mbps>) = Gbps.create(float value / 1000.)
        static member toTeraBitsPerSecond(value : float<Mbps>) = Tbps.create(float value / 1e+6)
        static member toKiloBytesPerSecond(value : float<Mbps>) = kBps.create(float value * 125.)
        static member toMegaBytesPerSecond(value : float<Mbps>) = MBps.create(float value / 8.)
        static member toGigaBytesPerSecond(value : float<Mbps>) = GBps.create(float value / 8000.)
        static member toTeraBytesPerSecond(value : float<Mbps>) = TBps.create(float value / 8e+6)
        static member toKibibitPerSecond(value : float<Mbps>) = Kibitps.create(float value * 977.)
        static member toMebibitPerSecond(value : float<Mbps>) = Mibit.create(float value / 1.049)
    and [<Measure>] Gbps = // Giga bits per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<Gbps> value
        static member toBitsPerSecond(value : float<Gbps>) = bps.create(float value * 1e+9)
        static member toKiloBitsPerSecond(value : float<Gbps>) = kbps.create(float value * 1e+6)
        static member toMegaBitsPerSecond(value : float<Gbps>) = Mbps.create(float value * 1000.)
        static member toTeraBitsPerSecond(value : float<Gbps>) = Tbps.create(float value / 1000.)
        static member toKiloBytesPerSecond(value : float<Gbps>) = kBps.create(float value * 125000.)
        static member toMegaBytesPerSecond(value : float<Gbps>) = MBps.create(float value * 125.)
        static member toGigaBytesPerSecond(value : float<Gbps>) = GBps.create(float value / 8.)
        static member toTeraBytesPerSecond(value : float<Gbps>) = TBps.create(float value / 8000.)
        static member toKibibitPerSecond(value : float<Gbps>) = Kibitps.create(float value * 976563.)
        static member toMebibitPerSecond(value : float<Gbps>) = Mibit.create(float value * 954.)
    and [<Measure>] Tbps = // Terra bits per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<Tbps> value
        static member toBitsPerSecond(value : float<Tbps>) = bps.create(float value * 1e+12)
        static member toKiloBitsPerSecond(value : float<Tbps>) = kbps.create(float value * 1e+9)
        static member toMegaBitsPerSecond(value : float<Tbps>) = Mbps.create(float value * 1e+6)
        static member toGigaBitsPerSecond(value : float<Tbps>) = Tbps.create(float value * 1000.)
        static member toKiloBytesPerSecond(value : float<Tbps>) = kBps.create(float value * 1.25e+8)
        static member toMegaBytesPerSecond(value : float<Tbps>) = MBps.create(float value * 125000.)
        static member toGigaBytesPerSecond(value : float<Tbps>) = GBps.create(float value / 125.)
        static member toTeraBytesPerSecond(value : float<Tbps>) = TBps.create(float value / 8.)
        static member toKibibitPerSecond(value : float<Tbps>) = Kibitps.create(float value * 9.766e+8)
        static member toMebibitPerSecond(value : float<Tbps>) = Mibit.create(float value * 953674.)
    and [<Measure>] kBps = // kilo byte per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<kBps> value
        static member toBitsPerSecond(value : float<kBps>) = bps.create(float value * 8000.)
        static member toKiloBitsPerSecond(value : float<kBps>) = kbps.create(float value * 8.)
        static member toMegaBitsPerSecond(value : float<kBps>) = Mbps.create(float value / 125.)
        static member toGigaBitsPerSecond(value : float<kBps>) = Gbps.create(float value / 125000.)
        static member toTeraBitsPerSecond(value : float<kBps>) = Tbps.create(float value / 1.25e+8)
        static member toMegaBytesPerSecond(value : float<kBps>) = MBps.create(float value / 1000.)
        static member toGigaBytesPerSecond(value : float<kBps>) = GBps.create(float value / 1e+6)
        static member toTeraBytesPerSecond(value : float<kBps>) = TBps.create(float value / 1e+9)
        static member toKibibitPerSecond(value : float<kBps>) = Kibitps.create(float value * 7.812)
        static member toMebibitPerSecond(value : float<kBps>) = Mibit.create(float value / 131.)
    and [<Measure>] MBps = // Mega byte per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<MBps> value
        static member toBitsPerSecond(value : float<MBps>) = bps.create(float value * 8e+6)
        static member toKiloBitsPerSecond(value : float<MBps>) = kbps.create(float value * 8000.)
        static member toMegaBitsPerSecond(value : float<MBps>) = Mbps.create(float value * 8.)
        static member toGigaBitsPerSecond(value : float<MBps>) = Gbps.create(float value / 125.)
        static member toTeraBitsPerSecond(value : float<MBps>) = Tbps.create(float value / 125000.)
        static member toKiloBytesPerSecond(value : float<MBps>) = kBps.create(float value * 1000.)
        static member toGigaBytesPerSecond(value : float<MBps>) = GBps.create(float value / 1000.)
        static member toTeraBytesPerSecond(value : float<MBps>) = TBps.create(float value / 1e+6)
        static member toKibibitPerSecond(value : float<MBps>) = Kibitps.create(float value * 7813.)
        static member toMebibitPerSecond(value : float<MBps>) = Mibit.create(float value * 7.629)
    and [<Measure>] GBps = // Giga byte per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<GBps> value
        static member toBitsPerSecond(value : float<GBps>) = bps.create(float value * 8e+9)
        static member toKiloBitsPerSecond(value : float<GBps>) = kbps.create(float value * 8e+6)
        static member toMegaBitsPerSecond(value : float<GBps>) = Mbps.create(float value * 8000.)
        static member toGigaBitsPerSecond(value : float<GBps>) = Gbps.create(float value * 8.)
        static member toTeraBitsPerSecond(value : float<GBps>) = Tbps.create(float value / 125.)
        static member toKiloBytesPerSecond(value : float<GBps>) = kBps.create(float value * 1e+6)
        static member toMegaBytesPerSecond(value : float<GBps>) = MBps.create(float value * 1000.)
        static member toTeraBytesPerSecond(value : float<GBps>) = TBps.create(float value / 1000.)
        static member toKibibitPerSecond(value : float<GBps>) = Kibitps.create(float value * 7.812e+6)
        static member toMebibitPerSecond(value : float<GBps>) = Mibit.create(float value * 7629.)
    and [<Measure>] TBps = // Tera byte per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<TBps> value
        static member toBitsPerSecond(value : float<TBps>) = bps.create(float value * 8e+12)
        static member toKiloBitsPerSecond(value : float<TBps>) = kbps.create(float value * 8e+9)
        static member toMegaBitsPerSecond(value : float<TBps>) = Mbps.create(float value * 8e+6)
        static member toGigaBitsPerSecond(value : float<TBps>) = Gbps.create(float value * 8000.)
        static member toTeraBitsPerSecond(value : float<TBps>) = Tbps.create(float value * 8.)
        static member toKiloBytesPerSecond(value : float<TBps>) = kBps.create(float value * 1e+9)
        static member toMegaBytesPerSecond(value : float<TBps>) = MBps.create(float value * 1e+6)
        static member toGigaBytesPerSecond(value : float<TBps>) = GBps.create(float value * 1000.)
        static member toKibibitPerSecond(value : float<TBps>) = Kibitps.create(float value * 7.812e+9)
        static member toMebibitPerSecond(value : float<TBps>) = Mibit.create(float value* 7.629e+6)
    and [<Measure>] Kibitps = // Kibibit per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<Kibitps> value
        static member toBitsPerSecond(value : float<Kibitps>) = bps.create(float value * 1024.)
        static member toKiloBitsPerSecond(value : float<Kibitps>) = kbps.create(float value * 1.024)
        static member toMegaBitsPerSecond(value : float<Kibitps>) = Mbps.create(float value / 977.)
        static member toGigaBitsPerSecond(value : float<Kibitps>) = Gbps.create(float value / 976562.)
        static member toTeraBitsPerSecond(value : float<Kibitps>) = Tbps.create(float value / 9.766e+8)
        static member toKiloBytesPerSecond(value : float<Kibitps>) = kBps.create(float value / 7.812)
        static member toMegaBytesPerSecond(value : float<Kibitps>) = MBps.create(float value / 7813.)
        static member toGigaBytesPerSecond(value : float<Kibitps>) = GBps.create(float value / 7.812e+6)
        static member toTeraBytesPerSecond(value : float<Kibitps>) = TBps.create(float value / 7.812e+9)
        static member toMebibitPerSecond(value : float<Kibitps>) = Mibit.create(float value / 1024.)
    and [<Measure>] Mibit = // Mebibit per second
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<Mibit> value
        static member toBitsPerSecond(value : float<Mibit>) = bps.create(float value * 1.049e+6)
        static member toKiloBitsPerSecond(value : float<Mibit>) = kbps.create(float value * 1049.)
        static member toMegaBitsPerSecond(value : float<Mibit>) = Mbps.create(float value * 1.049)
        static member toGigaBitsPerSecond(value : float<Mibit>) = Gbps.create(float value / 954.)
        static member toTeraBitsPerSecond(value : float<Mibit>) = Tbps.create(float value / 953674.)
        static member toKiloBytesPerSecond(value : float<Mibit>) = kBps.create(float value * 131.)
        static member toMegaBytesPerSecond(value : float<Mibit>) = MBps.create(float value / 7.629)
        static member toGigaBytesPerSecond(value : float<Mibit>) = GBps.create(float value / 7629.)
        static member toTeraBytesPerSecond(value : float<Mibit>) = TBps.create(float value / 7.629e+6)
        static member toKibibitPerSecond(value : float<Mibit>) = Kibitps.create(float value * 1024.)
        
