namespace FSharp.Units

open Microsoft.FSharp.Core

module Length =

    [<Measure>]
    type mm = // millimetres
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<mm> value
        static member toCentimetres(value : float<mm>) = cm.create(float value / 10.0)
        static member toMetres(value : float<mm>) = m.create(float value / 1000.0)
        static member toKilometres(value : float<mm>) = km.create(float value / 1000000.0)
        static member toInches(value : float<mm>) = inch.create(float value / 25.4)
        static member toFeet(value : float<mm>) = ft.create(float value / 304.8)
        static member toYards(value : float<mm>) = yard.create(float value / 914.4)
        static member toMiles(value : float<mm>) = mile.create(float value / 1609344.)
        static member toNauticalMiles(value : float<mm>) = NM.create(float value / 1852000.)
    and [<Measure>] cm = // centimetres
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<cm> value
        static member toMillimetres(value : float<cm>) = mm.create(float value * 10.0)
        static member toMetres(value : float<cm>) = m.create(float value / 100.0)
        static member toKilometres(value : float<cm>) = km.create(float value / 100000.0)
        static member toInches(value : float<cm>) = inch.create(float value / 2.54)
        static member toFeet(value : float<cm>) = ft.create(float value / 30.48)
        static member toYards(value : float<cm>) = yard.create(float value / 91.44)
        static member toMiles(value : float<cm>) = mile.create(float value / 160934.4)
        static member toNauticalMiles(value : float<cm>) = NM.create(float value / 185200.)
    and [<Measure>] m = // metres
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<m> value
        static member toMillimetres(value : float<m>) = mm.create(float value * 1000.0)
        static member toCentimetres(value : float<m>) = cm.create(float value * 100.0)
        static member toKilometres(value : float<m>) = km.create(float value / 1000.0)
        static member toInches(value : float<m>) = inch.create(float value / 0.0254)
        static member toFeet(value : float<m>) = ft.create(float value / 0.3048)
        static member toYards(value : float<m>) = yard.create(float value / 0.9144)
        static member toMiles(value : float<m>) = mile.create(float value / 1609.344)
        static member toNauticalMiles(value : float<m>) = NM.create(float value / 1852.)
    and [<Measure>] km = // kilometres
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<km> value
        static member toMillimetres(value : float<km>) = mm.create(float value * 1000000.0)
        static member toCentimetres(value : float<km>) = cm.create(float value * 100000.0)
        static member toMetres(value : float<km>) = m.create(float value * 1000.0)
        static member toInches(value : float<km>) = inch.create(float value / 0.0000254)
        static member toFeet(value : float<km>) = ft.create(float value / 0.0003048)
        static member toYards(value : float<km>) = yard.create(float value / 0.0009144)
        static member toMiles(value : float<km>) = mile.create(float value / 1.609344)
        static member toNauticalMiles(value : float<km>) = NM.create(float value / 1.85200)
    and [<Measure>] inch = // inches
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<inch> value
        static member toMillimetres(value : float<inch>) = mm.create(float value * 25.4)
        static member toCentimetres(value : float<inch>) = cm.create(float value * 2.54)
        static member toMetres(value : float<inch>) = m.create(float value * 0.0254)
        static member toKilometres(value : float<inch>) = km.create(float value * 0.0000254)
        static member toFeet(value : float<inch>) = ft.create(float value / 12.)
        static member toYards(value : float<inch>) = yard.create(float value / 36.)
        static member toMiles(value : float<inch>) = mile.create(float value / 63360.)
        static member toNauticalMiles(value : float<inch>) = NM.create(float value / 72913.4)
    and [<Measure>] ft = // feet
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<ft> value
        static member toMillimetres(value : float<ft>) = mm.create(float value * 304.8)
        static member toCentimetres(value : float<ft>) = cm.create(float value * 30.48)
        static member toMetres(value : float<ft>) = m.create(float value * 0.3048)
        static member toKilometres(value : float<ft>) = km.create(float value * 0.0003048)
        static member toInches(value : float<ft>) = inch.create(float value * 12.)
        static member toYards(value : float<ft>) = yard.create(float value / 3.)
        static member toMiles(value : float<ft>) = mile.create(float value / 5280.)
        static member toNauticalMiles(value : float<ft>) = NM.create(float value / 6076.12)
    and [<Measure>] yard = // yards
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<yard> value
        static member toMillimetres(value : float<yard>) = mm.create(float value * 914.4)
        static member toCentimetres(value : float<yard>) = cm.create(float value * 91.44)
        static member toMetres(value : float<yard>) = m.create(float value * 0.9144)
        static member toKilometres(value : float<yard>) = km.create(float value * 0.0009144)
        static member toInches(value : float<yard>) = inch.create(float value * 36.)
        static member toFeet(value : float<yard>) = ft.create(float value * 3.)
        static member toMiles(value : float<yard>) = mile.create(float value / 1760.)
        static member toNauticalMiles(value : float<yard>) = NM.create(float value / 2025.37)
    and [<Measure>] mile = // miles
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<mile> value
        static member toMillimetres(value : float<mile>) = mm.create(float value * 1609344.)
        static member toCentimetres(value : float<mile>) = cm.create(float value * 160934.4)
        static member toMetres(value : float<mile>) = m.create(float value * 1609.344)
        static member toKilometres(value : float<mile>) = km.create(float value * 1.609344)
        static member toInches(value : float<mile>) = inch.create(float value * 63360.)
        static member toFeet(value : float<mile>) = ft.create(float value * 5280.)
        static member toYards(value : float<mile>) = yard.create(float value * 1760.)
        static member toNauticalMiles(value : float<mile>) = NM.create(float value / 1.15078)
    and [<Measure>] NM  = // nautical mile symbol M, NM, Nm o nmi
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<NM> value
        static member toMillimetres(value : float<NM>) = mm.create(float value * 1852000.)
        static member toCentimetres(value : float<NM>) = cm.create(float value * 185200.)
        static member toMetres(value : float<NM>) = m.create(float value * 1852.)
        static member toKilometres(value : float<NM>) = km.create(float value * 1.85200)
        static member toInches(value : float<NM>) = inch.create(float value * 72913.4)
        static member toFeet(value : float<NM>) = ft.create(float value * 6076.12)
        static member toYards(value : float<NM>) = yard.create(float value * 2025.37)
        static member toMiles(value : float<NM>) = mile.create(float value * 1.15078)
    
