namespace FSharp.Units

open Microsoft.FSharp.Core

module Length =

    [<Measure>]
    type mm = // millimetres
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<mm> value
        static member toCentimetres(value : float<mm>) = value / 10.0<mm/cm>
        static member toMetres(value : float<mm>) = value / 1000.0<mm/m>
        static member toKilometres(value : float<mm>) = value / 1000000.0<mm/km>
        static member toInches(value : float<mm>) = value / 25.4<mm/inch>
        static member toFeet(value : float<mm>) = value / 304.8<mm/ft>
        static member toYards(value : float<mm>) = value / 914.4<mm/yard>
        static member toMiles(value : float<mm>) = value / 1609344.<mm/mile>
        static member toNauticalMiles(value : float<mm>) = value / 1852000.<mm/NM>
    and [<Measure>] cm = // centimetres
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<cm> value
        static member toMillimetres(value : float<cm>) = value * 10.0<mm/cm>
        static member toMetres(value : float<cm>) = value / 100.0<cm/m>
        static member toKilometres(value : float<cm>) = value / 100000.0<cm/km>
        static member toInches(value : float<cm>) = value / 2.54<cm/inch>
        static member toFeet(value : float<cm>) = value / 30.48<cm/ft>
        static member toYards(value : float<cm>) = value / 91.44<cm/yard>
        static member toMiles(value : float<cm>) = value / 160934.4<cm/mile>
        static member toNauticalMiles(value : float<cm>) = value / 185200.<cm/NM>
    and [<Measure>] m = // metres
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<m> value
        static member toMillimetres(value : float<m>) = value * 1000.0<mm/m>
        static member toCentimetres(value : float<m>) = value * 100.0<cm/m>
        static member toKilometres(value : float<m>) = value / 1000.0<m/km>
        static member toInches(value : float<m>) = value / 0.0254<m/inch>
        static member toFeet(value : float<m>) = value / 0.3048<m/ft>
        static member toYards(value : float<m>) = value / 0.9144<m/yard>
        static member toMiles(value : float<m>) = value / 1609.344<m/mile>
        static member toNauticalMiles(value : float<m>) = value / 1852.<m/NM>
    and [<Measure>] km = // kilometres
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<km> value
        static member toMillimetres(value : float<km>) = value * 1000000.0<mm/km>
        static member toCentimetres(value : float<km>) = value * 100000.0<cm/km>
        static member toMetres(value : float<km>) = value * 1000.0<m/km>
        static member toInches(value : float<km>) = value / 0.0000254<km/inch>
        static member toFeet(value : float<km>) = value / 0.0003048<km/ft>
        static member toYards(value : float<km>) = value / 0.0009144<km/yard>
        static member toMiles(value : float<km>) = value / 1.609344<km/mile>
        static member toNauticalMiles(value : float<km>) = value / 1.85200<km/NM>
    and [<Measure>] inch = // inches
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<inch> value
        static member toMillimetres(value : float<inch>) = value * 25.4<mm/inch>
        static member toCentimetres(value : float<inch>) = value * 2.54<cm/inch>
        static member toMetres(value : float<inch>) = value * 0.0254<m/inch>
        static member toKilometres(value : float<inch>) = value * 0.0000254<km/inch>
        static member toFeet(value : float<inch>) = value / 12.<inch/ft>
        static member toYards(value : float<inch>) = value / 36.<inch/yard>
        static member toMiles(value : float<inch>) = value / 63360.<inch/mile>
        static member toNauticalMiles(value : float<inch>) = value / 72913.4<inch/NM>
    and [<Measure>] ft = // feet
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<ft> value
        static member toMillimetres(value : float<ft>) = value * 304.8<mm/ft>
        static member toCentimetres(value : float<ft>) = value * 30.48<cm/ft>
        static member toMetres(value : float<ft>) = value * 0.3048<m/ft>
        static member toKilometres(value : float<ft>) = value * 0.0003048<km/ft>
        static member toInches(value : float<ft>) = value * 12.<inch/ft>
        static member toYards(value : float<ft>) = value / 3.<ft/yard>
        static member toMiles(value : float<ft>) = value / 5280.<ft/mile>
        static member toNauticalMiles(value : float<ft>) = value / 6076.12<ft/NM>
    and [<Measure>] yard = // yards
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<yard> value
        static member toMillimetres(value : float<yard>) = value * 914.4<mm/yard>
        static member toCentimetres(value : float<yard>) = value * 91.44<cm/yard>
        static member toMetres(value : float<yard>) = value * 0.9144<m/yard>
        static member toKilometres(value : float<yard>) = value * 0.0009144<km/yard>
        static member toInches(value : float<yard>) = value * 36.<inch/yard>
        static member toFeet(value : float<yard>) = value * 3.<ft/yard>
        static member toMiles(value : float<yard>) = value / 1760.<yard/mile>
        static member toNauticalMiles(value : float<yard>) = value / 2025.37<yard/NM>
    and [<Measure>] mile = // miles
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<mile> value
        static member toMillimetres(value : float<mile>) = value * 1609344.<mm/mile>
        static member toCentimetres(value : float<mile>) = value * 160934.4<cm/mile>
        static member toMetres(value : float<mile>) = value * 1609.344<m/mile>
        static member toKilometres(value : float<mile>) = value * 1.609344<km/mile>
        static member toInches(value : float<mile>) = value * 63360.<inch/mile>
        static member toFeet(value : float<mile>) = value * 5280.<ft/mile>
        static member toYards(value : float<mile>) = value * 1760.<yard/mile>
        static member toNauticalMiles(value : float<mile>) = value / 1.15078<mile/NM>
    and [<Measure>] NM  = // nautical mile symbol M, NM, Nm o nmi
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<NM> value
        static member toMillimetres(value : float<NM>) = value * 1852000.<mm/NM>
        static member toCentimetres(value : float<NM>) = value * 185200.<cm/NM>
        static member toMetres(value : float<NM>) = value * 1852.<m/NM>
        static member toKilometres(value : float<NM>) = value * 1.85200<km/NM>
        static member toInches(value : float<NM>) = value * 72913.4<inch/NM>
        static member toFeet(value : float<NM>) = value * 6076.12<ft/NM>
        static member toYards(value : float<NM>) = value * 2025.37<yard/NM>
        static member toMiles(value : float<NM>) = value * 1.15078<mile/NM>
    
