namespace FSharp.Units

open Microsoft.FSharp.Core

module Time = 

    [<Measure>]
    type second = // seconds
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<second> value
        static member toMinutes(value : float<second>) = minute.create(Utils.removeUnit(value / 60.0))
        static member toHours(value : float<second>) = hour.create(Utils.removeUnit(value / 3600.0))
        static member toDays(value : float<second>) = day.create(Utils.removeUnit(value / 86400.0))
        static member toWeeks(value : float<second>) = week.create(Utils.removeUnit(value / 604800.0))
        static member toMonths(value : float<second>) = month.create(Utils.removeUnit(value / 2.628e+6))
        static member toYears(value : float<second>) = year.create(Utils.removeUnit(value / 3.154e+7))
        static member toDecade(value : float<second>) = decade.create(Utils.removeUnit(value / 3.154e+8))
        static member toCentury(value : float<second>) = century.create(Utils.removeUnit(value / 3.154e+9))
    and  [<Measure>] minute = // minutes
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<minute> value
        static member toSeconds(value : float<second>) = second.create(Utils.removeUnit(value * 60.0))
        static member toHours(value : float<second>) = hour.create(Utils.removeUnit(value / 60.0))
        static member toDays(value : float<second>) = day.create(Utils.removeUnit(value / 1440.0))
        static member toWeeks(value : float<second>) = week.create(Utils.removeUnit(value / 10080.0))
        static member toMonths(value : float<second>) = month.create(Utils.removeUnit(value / 43800.0))
        static member toYears(value : float<second>) = year.create(Utils.removeUnit(value / 525600.0))
        static member toDecade(value : float<second>) = decade.create(Utils.removeUnit(value / 5.256e+6))
        static member toCentury(value : float<second>) = century.create(Utils.removeUnit(value / 5.256e+7))
    and  [<Measure>] hour = // hr
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<hour> value
        static member toSeconds(value : float<second>) = second.create(Utils.removeUnit(value * 3600.0))
        static member toMinutes(value : float<second>) = minute.create(Utils.removeUnit(value * 60.0))
        static member toDays(value : float<second>) = day.create(Utils.removeUnit(value / 24.0))
        static member toWeeks(value : float<second>) = week.create(Utils.removeUnit(value / 168.0))
        static member toMonths(value : float<second>) = month.create(Utils.removeUnit(value / 730.0))
        static member toYears(value : float<second>) = year.create(Utils.removeUnit(value / 8760.0))
        static member toDecade(value : float<second>) = decade.create(Utils.removeUnit(value / 87600.0))
        static member toCentury(value : float<second>) = century.create(Utils.removeUnit(value / 876000.0))
    and  [<Measure>] day = // day
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<day> value
        static member toSeconds(value : float<second>) = second.create(Utils.removeUnit(value * 86400.0))
        static member toMinutes(value : float<second>) = hour.create(Utils.removeUnit(value * 1440.0))
        static member toHours(value : float<second>) = hour.create(Utils.removeUnit(value * 24.0))
        static member toWeeks(value : float<second>) = week.create(Utils.removeUnit(value / 7.0))
        static member toMonths(value : float<second>) = month.create(Utils.removeUnit(value / 30.417))
        static member toYears(value : float<second>) = year.create(Utils.removeUnit(value / 365.0))
        static member toDecade(value : float<second>) = decade.create(Utils.removeUnit(value / 3650.0))
        static member toCentury(value : float<second>) = century.create(Utils.removeUnit(value / 36500.0))
    and  [<Measure>] week = // week
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<week> value
        static member toSeconds(value : float<second>) = second.create(Utils.removeUnit(value * 604800.0))
        static member toMinutes(value : float<second>) = hour.create(Utils.removeUnit(value * 10080.0))
        static member toHours(value : float<second>) = hour.create(Utils.removeUnit(value * 168.0))
        static member toDays(value : float<second>) = day.create(Utils.removeUnit(value * 7.0))
        static member toMonths(value : float<second>) = month.create(Utils.removeUnit(value / 4.345))
        static member toYears(value : float<second>) = year.create(Utils.removeUnit(value / 52.143))
        static member toDecade(value : float<second>) = decade.create(Utils.removeUnit(value / 521.0))
        static member toCentury(value : float<second>) = century.create(Utils.removeUnit(value / 5214.0))
    and  [<Measure>] month = // month 
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<month> value
        static member toSeconds(value : float<second>) = second.create(Utils.removeUnit(value * 2.628e+6))
        static member toMinutes(value : float<second>) = minute.create(Utils.removeUnit(value * 43800.0))
        static member toHours(value : float<second>) = hour.create(Utils.removeUnit(value * 730.0))
        static member toDays(value : float<second>) = day.create(Utils.removeUnit(value * 30.417))
        static member toWeeks(value : float<second>) = week.create(Utils.removeUnit(value * 4.345))
        static member toYears(value : float<second>) = year.create(Utils.removeUnit(value / 12.0))
        static member toDecade(value : float<second>) = decade.create(Utils.removeUnit(value / 120.0))
        static member toCentury(value : float<second>) = century.create(Utils.removeUnit(value / 1200.0))
    and  [<Measure>] year = // calendar year
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<year> value
        static member toSeconds(value : float<second>) = second.create(Utils.removeUnit(value * 3.154e+7))
        static member toMinutes(value : float<second>) = minute.create(Utils.removeUnit(value * 525600.0))
        static member toHours(value : float<second>) = hour.create(Utils.removeUnit(value * 8760.0))
        static member toDays(value : float<second>) = day.create(Utils.removeUnit(value * 365.0))
        static member toWeeks(value : float<second>) = week.create(Utils.removeUnit(value * 52.143))
        static member toMonths(value : float<second>) = year.create(Utils.removeUnit(value * 12.0))
        static member toDecade(value : float<second>) = decade.create(Utils.removeUnit(value / 10.0))
        static member toCentury(value : float<second>) = century.create(Utils.removeUnit(value / 100.0))
    and  [<Measure>] decade = // decade
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<decade> value
        static member toSeconds(value : float<second>) = second.create(Utils.removeUnit(value * 3.154e+8))
        static member toMinutes(value : float<second>) = minute.create(Utils.removeUnit(value * 5.256e+6))
        static member toHours(value : float<second>) = hour.create(Utils.removeUnit(value * 87600.0))
        static member toDays(value : float<second>) = day.create(Utils.removeUnit(value * 3650.0))
        static member toWeeks(value : float<second>) = week.create(Utils.removeUnit(value * 521.0))
        static member toMonths(value : float<second>) = year.create(Utils.removeUnit(value * 120.0))
        static member toYears(value : float<second>) = year.create(Utils.removeUnit(value * 10.0))
        static member toCentury(value : float<second>) = century.create(Utils.removeUnit(value / 10.0))
    and  [<Measure>] century = // century
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<century> value
        static member toSeconds(value : float<second>) = second.create(Utils.removeUnit(value * 3.154e+9))
        static member toMinutes(value : float<second>) = minute.create(Utils.removeUnit(value * 5.256e+7))
        static member toHours(value : float<second>) = hour.create(Utils.removeUnit(value * 876000.0))
        static member toDays(value : float<second>) = day.create(Utils.removeUnit(value * 36500.0))
        static member toWeeks(value : float<second>) = week.create(Utils.removeUnit(value * 5214.0))
        static member toMonths(value : float<second>) = year.create(Utils.removeUnit(value * 1200.0))
        static member toYears(value : float<second>) = year.create(Utils.removeUnit(value * 100.0))
        static member toDecade(value : float<second>) = decade.create(Utils.removeUnit(value * 10.0))
