// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace FSharp.Units

open Microsoft.FSharp.Core

module Force =

    /// Dynes (dyn) units
    [<Measure>]
    type dyn =
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<dyn> value
        /// Converts the supplied Dynes value to Newtons
        static member toNewtons(value : float<dyn>) = N.create(float value / 100000.0)
        /// Converts the supplied Dynes value to Poundals
        static member toPoundals(value : float<dyn>) = pdl.create(float value / 13825.4954376)
        /// Converts the supplied Dynes value to Kilogram-force
        static member toKilogramforce(value : float<dyn>) = kp.create(float value / 980665.0)
    and /// Kilogram-force (kp) units
        [<Measure>] kp =
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<kp> value
        /// Converts the supplied Kilogram-force value to Newtons
        static member toNewtons(value : float<kp>) = N.create(float value * 9.80665)
        /// Converts the supplied Kilogram-force value to Dynes
        static member toDynes(value : float<kp>) = dyn.create(float value * 980665.0)
        /// Converts the supplied Kilogram-force value to Poundals
        static member toPoundals(value : float<kp>) = pdl.create(float value * 70.93163528397)
    and /// Newtons (N) units
        [<Measure>] N =
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<N> value
        /// Converts the supplied Newtons value to Dynes
        static member toDynes(value : float<N>) = dyn.create(float value * 100000.0)
        /// Converts the supplied Newtons value to Poundals
        static member toPoundals(value : float<N>) = pdl.create(float value * 7.23301)
        /// Converts the supplied Newtons value to Kilogram-force
        static member toKilogramforce(value : float<N>) = kp.create(float value / 9.80665)
    and /// Poundals (pdl) units
        [<Measure>] pdl =
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<pdl> value
        /// Converts the supplied Poundals value to Newtons
        static member toNewtons(value : float<pdl>) = N.create(float value / 7.23301)
        /// Converts the supplied Poundals value to Dynes
        static member toDynes(value : float<pdl>) = dyn.create(float value * 13825.4954376)
        /// Converts the supplied Poundals value to Kilogram-force
        static member toKilogramforce(value : float<pdl>) = kp.create(float value / 70.93163528397)
