// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

namespace FSharp.Units

open Microsoft.FSharp.Core

module FuelEconomy =

    /// Kilometre Per Litre (kml) units
    [<Measure>]
    type kml =
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<kml> value
        /// Converts the supplied Kilometre Per Litre value to US Miles Per Gallon
        static member toUSMilesPerGallon(value : float<kml>) = usmpg.create(float value * 2.35215)
        /// Converts the supplied Kilometre Per Litre value to Miles Per Gallon
        static member toMilesPerGallon(value : float<kml>) = mpg.create(float value * 2.82481)
    and /// Miles Per Gallon (mpg) units
        [<Measure>] mpg =
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<mpg> value
        /// Converts the supplied Miles Per Gallon value to Kilometre Per Litre
        static member toKilometrePerLitre(value : float<mpg>) = kml.create(float value / 2.82481)
        /// Converts the supplied Miles Per Gallon value to US Miles Per Gallon
        static member toUSMilesPerGallon(value : float<mpg>) = usmpg.create(float value / 1.20095)
    and /// US Miles Per Gallon (usmpg) units
        [<Measure>] usmpg =
        static member create(value : float) = LanguagePrimitives.FloatWithMeasure<usmpg> value
        /// Converts the supplied US Miles Per Gallon value to Kilometre Per Litre
        static member toKilometrePerLitre(value : float<usmpg>) = kml.create(float value / 2.35215)
        /// Converts the supplied US Miles Per Gallon value to Miles Per Gallon
        static member toMilesPerGallon(value : float<usmpg>) = mpg.create(float value * 1.20095)
