name: Build FSharp.Units

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Manual Run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test FSharp.Units.Tests/FSharp.Units.Tests.fsproj --no-restore --verbosity normal
    - name: Create Package
      run: dotnet pack --configuration Release
    - name: Create Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FSharp.Units
        path: /home/runner/work/FSharp.Units/FSharp.Units/FSharp.Units/bin/Release/FSharp.Units.*.nupkg
