name: Build FSharp.Units

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # Manual Run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test FSharp.Units.Tests/FSharp.Units.Tests.fsproj --no-restore --verbosity normal
    - name: Create Package
      run: dotnet pack --configuration Release
    - name: Create Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FSharp.Units
        path: /home/runner/work/FSharp.Units/FSharp.Units/FSharp.Units/bin/Release/FSharp.Units.*.nupkg
    - name: Publish to Nuget
      run: dotnet nuget push /home/runner/work/FSharp.Units/FSharp.Units/FSharp.Units/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
    - name: Publish to GitHub
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/putridparrot/index.json -n github -u putridparrot -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        dotnet nuget push /home/runner/work/FSharp.Units/FSharp.Units/FSharp.Units/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.GITHUB_TOKEN}} --source "github"
